"""initial palm schema

Revision ID: 0b06d8e2345c
Revises: 
Create Date: 2026-07-07 16:59:55.824081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0b06d8e2345c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxon',
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('ipni_lsid', sa.String(), nullable=True),
    sa.Column('wcvp_id', sa.String(), nullable=True),
    sa.Column('gbif_taxon_key', sa.Integer(), nullable=True),
    sa.Column('iucn_taxon_id', sa.String(), nullable=True),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('authorship', sa.String(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('genus', sa.String(), nullable=True),
    sa.Column('tribe', sa.String(), nullable=True),
    sa.Column('subfamily', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('is_hybrid', sa.Boolean(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('species_id'),
    sa.UniqueConstraint('ipni_lsid')
    )
    op.create_index(op.f('ix_taxon_gbif_taxon_key'), 'taxon', ['gbif_taxon_key'], unique=False)
    op.create_index(op.f('ix_taxon_genus'), 'taxon', ['genus'], unique=False)
    op.create_index(op.f('ix_taxon_scientific_name'), 'taxon', ['scientific_name'], unique=False)
    op.create_index(op.f('ix_taxon_slug'), 'taxon', ['slug'], unique=True)
    op.create_index(op.f('ix_taxon_subfamily'), 'taxon', ['subfamily'], unique=False)
    op.create_index(op.f('ix_taxon_tribe'), 'taxon', ['tribe'], unique=False)
    op.create_index(op.f('ix_taxon_wcvp_id'), 'taxon', ['wcvp_id'], unique=False)
    op.create_table('tree',
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('citation_doi', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tree_id')
    )
    op.create_table('climate_profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('cmmt_mean', sa.Float(), nullable=True),
    sa.Column('cmmt_min', sa.Float(), nullable=True),
    sa.Column('precip_mean_mm', sa.Float(), nullable=True),
    sa.Column('n_occurrences', sa.Integer(), nullable=True),
    sa.Column('hardiness_c', sa.Float(), nullable=True),
    sa.Column('hardiness_zone', sa.String(), nullable=True),
    sa.Column('derived', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['taxon.species_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_climate_profile_species_id'), 'climate_profile', ['species_id'], unique=True)
    op.create_table('conservation_assessment',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('risk_basis', sa.String(), nullable=True),
    sa.Column('iucn_category', sa.String(), nullable=True),
    sa.Column('predicted_category', sa.String(), nullable=True),
    sa.Column('prediction_probability', sa.Float(), nullable=True),
    sa.Column('criteria', sa.String(), nullable=True),
    sa.Column('assessment_year', sa.Integer(), nullable=True),
    sa.Column('population_trend', sa.String(), nullable=True),
    sa.Column('threats', sa.JSON(), nullable=True),
    sa.Column('exsitu_collections_count', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['taxon.species_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index(op.f('ix_conservation_assessment_species_id'), 'conservation_assessment', ['species_id'], unique=False)
    op.create_table('genetic_resource',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('accession', sa.String(), nullable=True),
    sa.Column('genome_size_bp', sa.Integer(), nullable=True),
    sa.Column('ploidy', sa.Integer(), nullable=True),
    sa.Column('chromosome_2n', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['taxon.species_id'], ),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_genetic_resource_species_id'), 'genetic_resource', ['species_id'], unique=False)
    op.create_table('name_alias',
    sa.Column('alias_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=False),
    sa.Column('authorship', sa.String(), nullable=True),
    sa.Column('name_status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['taxon.species_id'], ),
    sa.PrimaryKeyConstraint('alias_id')
    )
    op.create_index(op.f('ix_name_alias_raw_name'), 'name_alias', ['raw_name'], unique=False)
    op.create_index(op.f('ix_name_alias_species_id'), 'name_alias', ['species_id'], unique=False)
    op.create_table('occurrence',
    sa.Column('occurrence_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('coordinate_uncertainty_m', sa.Float(), nullable=True),
    sa.Column('basis_of_record', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('quality_flags', sa.JSON(), nullable=True),
    sa.Column('dataset_key', sa.String(), nullable=True),
    sa.Column('in_native_range', sa.Boolean(), nullable=False),
    sa.Column('establishment_means', sa.String(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('cmmt', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['taxon.species_id'], ),
    sa.PrimaryKeyConstraint('occurrence_id')
    )
    op.create_index(op.f('ix_occurrence_establishment_means'), 'occurrence', ['establishment_means'], unique=False)
    op.create_index(op.f('ix_occurrence_in_native_range'), 'occurrence', ['in_native_range'], unique=False)
    op.create_index(op.f('ix_occurrence_species_id'), 'occurrence', ['species_id'], unique=False)
    op.create_table('photo',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('attribution', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['taxon.species_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_index(op.f('ix_photo_species_id'), 'photo', ['species_id'], unique=False)
    op.create_table('phylogeny_node',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('parent_node_id', sa.Integer(), nullable=True),
    sa.Column('is_tip', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('branch_length', sa.Float(), nullable=True),
    sa.Column('support', sa.Float(), nullable=True),
    sa.Column('conflict', sa.Boolean(), nullable=False),
    sa.Column('placement', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('tip_label', sa.String(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('clade_label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_node_id'], ['phylogeny_node.node_id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['taxon.species_id'], ),
    sa.ForeignKeyConstraint(['tree_id'], ['tree.tree_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index(op.f('ix_phylogeny_node_tree_id'), 'phylogeny_node', ['tree_id'], unique=False)
    op.create_table('range_region',
    sa.Column('range_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('tdwg_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['taxon.species_id'], ),
    sa.PrimaryKeyConstraint('range_id')
    )
    op.create_index(op.f('ix_range_region_species_id'), 'range_region', ['species_id'], unique=False)
    op.create_index(op.f('ix_range_region_tdwg_code'), 'range_region', ['tdwg_code'], unique=False)
    op.create_table('trait',
    sa.Column('trait_record_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('trait_name', sa.String(), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_cat', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('n_observations', sa.Integer(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['taxon.species_id'], ),
    sa.PrimaryKeyConstraint('trait_record_id')
    )
    op.create_index(op.f('ix_trait_species_id'), 'trait', ['species_id'], unique=False)
    op.create_index(op.f('ix_trait_trait_name'), 'trait', ['trait_name'], unique=False)
    op.create_table('use',
    sa.Column('use_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('use_category', sa.String(), nullable=False),
    sa.Column('part_used', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('evidence_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['taxon.species_id'], ),
    sa.PrimaryKeyConstraint('use_id')
    )
    op.create_index(op.f('ix_use_species_id'), 'use', ['species_id'], unique=False)
    op.create_index(op.f('ix_use_use_category'), 'use', ['use_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_use_use_category'), table_name='use')
    op.drop_index(op.f('ix_use_species_id'), table_name='use')
    op.drop_table('use')
    op.drop_index(op.f('ix_trait_trait_name'), table_name='trait')
    op.drop_index(op.f('ix_trait_species_id'), table_name='trait')
    op.drop_table('trait')
    op.drop_index(op.f('ix_range_region_tdwg_code'), table_name='range_region')
    op.drop_index(op.f('ix_range_region_species_id'), table_name='range_region')
    op.drop_table('range_region')
    op.drop_index(op.f('ix_phylogeny_node_tree_id'), table_name='phylogeny_node')
    op.drop_table('phylogeny_node')
    op.drop_index(op.f('ix_photo_species_id'), table_name='photo')
    op.drop_table('photo')
    op.drop_index(op.f('ix_occurrence_species_id'), table_name='occurrence')
    op.drop_index(op.f('ix_occurrence_in_native_range'), table_name='occurrence')
    op.drop_index(op.f('ix_occurrence_establishment_means'), table_name='occurrence')
    op.drop_table('occurrence')
    op.drop_index(op.f('ix_name_alias_species_id'), table_name='name_alias')
    op.drop_index(op.f('ix_name_alias_raw_name'), table_name='name_alias')
    op.drop_table('name_alias')
    op.drop_index(op.f('ix_genetic_resource_species_id'), table_name='genetic_resource')
    op.drop_table('genetic_resource')
    op.drop_index(op.f('ix_conservation_assessment_species_id'), table_name='conservation_assessment')
    op.drop_table('conservation_assessment')
    op.drop_index(op.f('ix_climate_profile_species_id'), table_name='climate_profile')
    op.drop_table('climate_profile')
    op.drop_table('tree')
    op.drop_index(op.f('ix_taxon_wcvp_id'), table_name='taxon')
    op.drop_index(op.f('ix_taxon_tribe'), table_name='taxon')
    op.drop_index(op.f('ix_taxon_subfamily'), table_name='taxon')
    op.drop_index(op.f('ix_taxon_slug'), table_name='taxon')
    op.drop_index(op.f('ix_taxon_scientific_name'), table_name='taxon')
    op.drop_index(op.f('ix_taxon_genus'), table_name='taxon')
    op.drop_index(op.f('ix_taxon_gbif_taxon_key'), table_name='taxon')
    op.drop_table('taxon')
    op.drop_table('data_source')
    # ### end Alembic commands ###
